DEBUG = True
SECRET_KEY = '12345666'
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:root@127.0.0.1:3306/atm?charset=utf8mb4'
#SESSION_COOKIE_NAME = ''
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_POOL_RECYCLE = 8

